# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_jsonb_step_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='score_dict',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='killboard_pve',
        ),
        migrations.RemoveField(
            model_name='player',
            name='killboard_pvp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sorties_cls',
        ),
        migrations.RemoveField(
            model_name='playeraircraft',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='playeraircraft',
            name='killboard_pve',
        ),
        migrations.RemoveField(
            model_name='playeraircraft',
            name='killboard_pvp',
        ),
        migrations.RemoveField(
            model_name='playermission',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='playermission',
            name='killboard_pve',
        ),
        migrations.RemoveField(
            model_name='playermission',
            name='killboard_pvp',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='debug',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='killboard_pve',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='killboard_pvp',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='score_dict',
        ),
    ]
