# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_auto_20160404_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='stats.Squad'),
        ),
    ]
