# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_squad_max_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=128, unique=True, verbose_name='function name')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='title')),
                ('title_de', models.CharField(max_length=256, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=256, null=True, verbose_name='title')),
                ('type', models.CharField(choices=[('tour', 'tour'), ('mission', 'mission'), ('sortie', 'sortie')], default='tour', max_length=8, verbose_name='type')),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('desc_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('desc_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('desc_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('img', models.ImageField(upload_to='awards/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'awards',
                'verbose_name': 'award',
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Award')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
            options={
                'db_table': 'rewards',
                'verbose_name': 'reward',
                'verbose_name_plural': 'rewards',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reward',
            unique_together=set([('award', 'player')]),
        ),
    ]
