# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:19
from __future__ import unicode_literals

from django.db import migrations


def awards_example(apps, schema_editor):

    Award = apps.get_model('stats', 'Award')

    Award.objects.create(
        func='fighter_ace',
        title='Fighter Ace',
        title_en='Fighter Ace',
        title_ru='Лётчик-ас',
        type='tour',
        desc='streak 100',
        desc_en='streak 100',
        desc_ru='стрик 100',
        img='/static/img/example_award.png'
    )

    Award.objects.create(
        func='fighter_hero',
        title='Fighter Hero',
        title_en='Fighter Hero',
        title_ru='Герой-истребитель',
        type='sortie',
        desc='5 airkills in a single sortie',
        desc_en='5 airkills in a single sortie',
        desc_ru='5 сбитых за один вылет',
        img='/static/img/example_award.png'
    )

    Award.objects.create(
        func='mission_hero',
        title='Mission Hero',
        title_en='Mission Hero',
        title_ru='Герой миссии',
        type='mission',
        desc='15 airkills in one mission',
        desc_en='15 airkills in one mission',
        desc_ru='15 сбитых за одну миссию',
        img='/static/img/example_award.png'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_awards_functional'),
    ]

    operations = [
        migrations.RunPython(awards_example),
    ]
