# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_awards_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sorties_streak_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sorties_streak_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='award',
            name='img',
            field=models.ImageField(help_text='Image size should be 180x180', upload_to='awards/', verbose_name='image'),
        ),
    ]
