# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_mission_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
