# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_sortie_is_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='flight_time',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playeraircraft',
            name='flight_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermission',
            name='flight_time',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='flight_time',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='rating',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='score',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
