# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_big_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='desc_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_es',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='object',
            name='name_es',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_es',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
