# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


def set_0(apps, schema_editor):
    Player = apps.get_model('stats', 'Player')
    Player.objects.all().update(ft_streak_current=0,
                               ft_streak_max=0,
                               sortie_max_ak=0,
                               sortie_max_gk=0,
                               lost_aircraft_current=0)


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_spanish'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ft_streak_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ft_streak_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='lost_aircraft_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sortie_max_ak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sortie_max_gk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_0),
    ]
