# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_new_pilot_params_step_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ft_streak_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ft_streak_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lost_aircraft_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='sortie_max_ak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='sortie_max_gk',
            field=models.IntegerField(default=0),
        ),
    ]
