# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_vlifes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlife',
            name='aircraft_status',
            field=models.CharField(choices=[('unharmed', 'unharmed'), ('damaged', 'damaged'), ('destroyed', 'destroyed')], default='unharmed', max_length=12),
        ),
        migrations.AddField(
            model_name='vlife',
            name='bot_status',
            field=models.CharField(choices=[('healthy', 'healthy'), ('wounded', 'wounded'), ('dead', 'dead')], default='healthy', max_length=12),
        ),
        migrations.AlterField(
            model_name='vlife',
            name='status',
            field=models.CharField(choices=[('landed', 'landed'), ('ditched', 'ditched'), ('crashed', 'crashed'), ('shotdown', 'shotdown'), ('not_takeoff', 'not takeoff'), ('in_flight', 'in flight')], default='not_takeoff', max_length=12),
        ),
    ]
