# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_vlifes_step_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlife',
            name='relive',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
