# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_mod_rating_by_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ai_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
