# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0006_french'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='content_es',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
