# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0007_spanish'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='content_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='title_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
