# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 15:45
from __future__ import unicode_literals

from django.db import migrations
import stuff.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS citext'),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=stuff.fields.CaseInsensitiveEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=stuff.fields.CaseInsensitiveCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Username must match the name in the game IL-2 (including squad tag).', max_length=64, unique=True, verbose_name='username'),
        ),
    ]
