# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 11:36
from __future__ import unicode_literals

from django.db import migrations
import stuff.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ci_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=stuff.fields.CaseInsensitiveEmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=stuff.fields.CaseInsensitiveCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Username must match the name in the game IL-2 (including squad tag).', max_length=128, unique=True, verbose_name='username'),
        ),
    ]
