# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import squads.models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='join_code',
            field=models.CharField(default=squads.models.get_join_code, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='squad_member', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
